const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('downloader', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: s => ipcRenderer.invoke('settings:save', s),
  checkTools: () => ipcRenderer.invoke('tools:check'),
  updateYtDlp: () => ipcRenderer.invoke('tools:update-ytdlp'),
  sniffVideo: url => ipcRenderer.invoke('video:sniff', url),
  sniffPlaylist: url => ipcRenderer.invoke('video:sniff-playlist', url),
  calculateHash: filePath => ipcRenderer.invoke('file:hash', filePath),
  testProxy: proxyUrl => ipcRenderer.invoke('network:test-proxy', proxyUrl),
  toggleFloatingWidget: enable => ipcRenderer.invoke('widget:toggle', enable),
  pickDirectory: () => ipcRenderer.invoke('dialog:directory'),
  pickCookieFile: () => ipcRenderer.invoke('dialog:cookie-file'),
  importCookies: (site, path) => ipcRenderer.invoke('cookies:import', site, path),
  deleteCookies: site => ipcRenderer.invoke('cookies:delete', site),
  listCookies: () => ipcRenderer.invoke('cookies:list'),
  openLoginWindow: site => ipcRenderer.invoke('cookies:login-window', site),
  addTask: p => ipcRenderer.invoke('download:add', p),
  addBatch: p => ipcRenderer.invoke('download:add-batch', p),
  pause: id => ipcRenderer.invoke('download:pause', id),
  resume: id => ipcRenderer.invoke('download:resume', id),
  cancel: id => ipcRenderer.invoke('download:cancel', id),
  all: a => ipcRenderer.invoke('download:all', a),
  list: () => ipcRenderer.invoke('tasks:list'),
  open: p => ipcRenderer.invoke('shell:open', p),
  show: p => ipcRenderer.invoke('shell:show', p),
  openExternal: url => ipcRenderer.invoke('shell:open-external', url),
  shutdown: () => ipcRenderer.invoke('system:shutdown'),
  extractUrls: text => ipcRenderer.invoke('text:extract-urls', text),
  showMainWindow: () => ipcRenderer.invoke('window:show'),
  moveFloatingWindow: (dx, dy) => ipcRenderer.send('floating:move', { dx, dy }),
  dropTarget: text => ipcRenderer.invoke('floating:drop-target', text),
  getUserscript: () => ipcRenderer.invoke('browser:get-userscript'),
  getLanInfo: () => ipcRenderer.invoke('lan:info'),
  prioritizeTask: id => ipcRenderer.invoke('task:prioritize', id),
  trimVideo: opt => ipcRenderer.invoke('tools:trim-video', opt),
  exportGif: opt => ipcRenderer.invoke('tools:export-gif', opt),
  convertMedia: opt => ipcRenderer.invoke('tools:convert-media', opt),
  getClipboardHistory: () => ipcRenderer.invoke('clipboard:get-history'),
  clearClipboardHistory: () => ipcRenderer.invoke('clipboard:clear-history'),
  deleteClipboardItem: id => ipcRenderer.invoke('clipboard:delete-item', id),
  refreshTaskUrl: (id, newUrl) => ipcRenderer.invoke('download:refresh-url', { id, newUrl }),
  deleteTask: (id, deleteFile = false) => ipcRenderer.invoke('download:delete-task', { id, deleteFile }),
  clearCompleted: () => ipcRenderer.invoke('download:clear-completed'),
  parseTorrent: input => ipcRenderer.invoke('torrent:parse', input),
  pickTorrentFile: () => ipcRenderer.invoke('dialog:torrent-file'),
  updateTrackers: () => ipcRenderer.invoke('torrent:update-trackers'),
  syncOnlineTrackers: () => ipcRenderer.invoke('torrent:sync-online-trackers'),
  getTrackers: () => ipcRenderer.invoke('torrent:get-trackers'),
  openWebSniffer: url => ipcRenderer.invoke('websniffer:open', url),
  closeWebSniffer: () => ipcRenderer.invoke('websniffer:close'),
  getSniffedStreams: () => ipcRenderer.invoke('websniffer:get-streams'),
  scrapeAssets: () => ipcRenderer.invoke('websniffer:scrape-assets'),
  exportExtension: () => ipcRenderer.invoke('extension:export'),
  openExtensionGuide: () => ipcRenderer.invoke('extension:open-guide'),
  onUpdate: cb => ipcRenderer.on('task:update', (_, t) => cb(t)),
  onRemove: cb => ipcRenderer.on('task:remove', (_, id) => cb(id)),
  onClipboardDetected: cb => ipcRenderer.on('clipboard:detected', (_, data) => cb(data)),
  onClipboardHistoryUpdated: cb => ipcRenderer.on('clipboard:history-updated', (_, h) => cb(h)),
  onStreamDetected: cb => ipcRenderer.on('websniffer:stream-detected', (_, s) => cb(s)),
  onSpeedLimitChanged: cb => ipcRenderer.on('schedule:speed-limit-changed', (_, d) => cb(d)),
  onExternalAddTask: cb => ipcRenderer.on('external:add-task', (_, d) => cb(d)),
  onFloatingStats: cb => ipcRenderer.on('floating:stats', (_, d) => cb(d))
});
